services:
  mysql:
    image: mysql
    container_name: mysql-picpay
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=picpaydb
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: